# TimeWeb Cloud Apps Configuration
runtime: nodejs
version: 18

build:
  commands:
    - npm ci
    - npm run build

deploy:
  source: dist/

# SPA routing configuration
routes:
  - src: "/(.*)"
    dest: "/index.html"

# Static files caching
headers:
  - src: "/assets/(.*)"
    headers:
      - key: "Cache-Control"
        value: "public, max-age=31536000, immutable"
  - src: "\\.(jpg|jpeg|png|gif|svg|webp|avifs|ico)$"
    headers:
      - key: "Cache-Control"
        value: "public, max-age=31536000, immutable"
  - src: "\\.(woff|woff2|ttf|otf|eot)$"
    headers:
      - key: "Cache-Control"
        value: "public, max-age=31536000, immutable"
